//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.borrowBooks = new HashSet<borrowBook>();
            this.ReadingBooks = new HashSet<ReadingBook>();
            this.WishLists = new HashSet<WishList>();
        }
    
        
        public int Book_ID { get; set; }
        [Required]
        public string title { get; set; }
        [Required]
        public string author { get; set; }
        [Required]
        public string publisher { get; set; }
        [Required]
        public string category { get; set; }
        [Required]
        public Nullable<int> edition { get; set; }
        [Required]
        public Nullable<int> NoOfpages { get; set; }
        [Required]
        public int NoOfCopies { get; set; }
        [Required]
        public bool Available { get; set; }
        [Required]
        public int shelfNo { get; set; }
        [Required]
        public Nullable<System.DateTime> arrivedDate { get; set; }
        [Required]
        public Nullable<System.DateTime> Publishing_date { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrowBook> borrowBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadingBook> ReadingBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
