//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.borrowBooks = new HashSet<borrowBook>();
            this.ReadingBooks = new HashSet<ReadingBook>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int Book_ID { get; set; }
        [Display(Name = "Title  ")]
        public string title { get; set; }
        [Display(Name = "Author  ")]
        public string author { get; set; }
        [Display(Name = "Publisher  ")]
        public string publisher { get; set; }
        [Display(Name = "Category  ")]
        public string category { get; set; }
        [Display(Name = "Edition  ")]
        public Nullable<int> edition { get; set; }
        public Nullable<int> NoOfpages { get; set; }
        [Display(Name = "Number Of Pages  ")]
        public int NoOfCopies { get; set; }
        public bool Available { get; set; }
        [Display(Name = "Shelft Number  ")]
        public int shelfNo { get; set; }
        public Nullable<System.DateTime> arrivedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrowBook> borrowBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadingBook> ReadingBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
