//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public int Login_No { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual User User { get; set; }
    }
}
