//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.borrowBooks = new HashSet<borrowBook>();
            this.ReadingBooks = new HashSet<ReadingBook>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int Member_ID { get; set; }
        [Display(Name = "Name : ")]
        public string FullName { get; set; }
        [Display(Name = "Email: ")]
        public string Email { get; set; }
         [Display(Name = "Address : ")]
        public string Address { get; set; }
         [Display(Name = "Phone Number : ")]
         [RegularExpression("[0-9]{11}", ErrorMessage = "Please nter correct phone number")]
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrowBook> borrowBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadingBook> ReadingBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
