//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.borrowBooks = new HashSet<borrowBook>();
        }
    
        public int User_ID { get; set; }
        [Required]
        public string firstname { get; set; }
        [Required]
        public string middlename { get; set; }
        [Required]
        public string lastname { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        [Required]
        public System.DateTime birthdate { get; set; }
        [Required]
        public string address { get; set; }
        [Required]
        [Phone]
        public string phoneNo { get; set; }
        public int employeeType { get; set; }
        public Nullable<double> salary { get; set; }
    
        public virtual EmployeeType EmployeeType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<borrowBook> borrowBooks { get; set; }
    }
}
